---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-svc
  labels:
    app: kafka-connect-svc
  namespace: kafka
spec:
  clusterIP: None
  ports:
    - name: '8083'
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: kafka-connect

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka-connect
  serviceName: kafka-connect-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
    ### TODO: add JMX plugin to gather metrics
      containers:
        - name: kafka-connect-container
          image: kafkakraft/kafkakraft-connect:3.4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
          env: []
          volumeMounts:
          - name: kafka-connect-storage-data
            mountPath: /mnt/kafka
  volumeClaimTemplates:
  - metadata:
      name: kafka-connect-storage-data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
