name: build and push on merge

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: build
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push KafkaKRaft
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: kafkakraft/kafkakraft:latest

      - name: Build and push Kafka-Connect
        uses: docker/build-push-action@v3
        with:
          file: ./kafka-connect/Dockerfile
          push: true
          tags: kafkakraft/kafka-connect:latest

      - name: Printout status
        run: echo "Images builded + pushed to registry."
