name: build + push to dockerhub

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: vara
        id: vars
        shell: bash
        run: |
          echo "::set-output name=tags_list::kafkakraft/kafkakraft:$(echo ${GITHUB_SHA} | cut -c1-12),kafkakraft/kafkakraft:latest"

      - name: build+push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.vars.outputs.tags_list }}

      - name: img digest
        run: echo ${{ steps.docker_build.outputs.digest }}
