name: merge tests

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - './.gitignore'
      - '.github/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: build
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: DryRun docker build and push for KafkaKRaft in ./
        uses: docker/build-push-action@v3
        with:
          push: false
          file: ./manifests/kafka/Dockerfile
          tags: kafkakraft/kafkakraft:latest

      - name: DryRun docker build and push for Kafka-Connect in ./kafka-connect
        uses: docker/build-push-action@v3
        with:
          push: false
          file: ./manifests/connect/Dockerfile
          tags: kafkakraft/kafkakraft-connect:latest

      - name: Printout status
        run: echo "Images are buildable and can be pushed to registry."
